version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.1  # or any image relevant to your project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest
workflows:
  version: 2
  test:
    jobs:
      - build
